#!/bin/sh
set -e

if [ "$1" = "reload" ]; then
	/usr/local/bin/php /apps/bin/start_swoole_server.php reload
fi

if [ "$3" = 'start' ]; then
	if [ "$4" = '-d' ]; then
		echo "start -d not support"
		exit 0
	fi
	/usr/local/bin/php /apps/bin/start_swoole_server.php start --debug
fi

if [ "${1#/}" != "$1" ]; then
	exec "$@"
fi

/usr/local/bin/php /apps/bin/start_swoole_server.php start
