#!/bin/sh
set -e

echo "\n"
echo "-----------------------------------------"
echo "Start generating autoload files......"
cd /apps && /usr/bin/composer dumpautoload
echo "Success generating autoload files......"
echo "-----------------------------------------"

if [ "$1" = "start" ]; then
	/usr/local/bin/php /apps/bin/start_swoole_server.php "$@"
fi

if [ "$1" = '--debug' ]; then
	/usr/local/bin/php /apps/bin/start_swoole_server.php start --debug
fi

if [ "${1#/}" != "$1" ]; then
	exec "$@"
fi

if [ "$ENV" = 'dev' ]; then
	/usr/local/bin/php /apps/bin/start_swoole_server.php start --debug
fi

/usr/local/bin/php /apps/bin/start_swoole_server.php start
